---
- name: Install any necessary dependencies [Debian/Ubuntu]
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Import InfluxData GPG signing key [Debian/Ubuntu]
  ansible.builtin.apt_key:
    url: "{{ telegraf_repo_base_url }}/influxdb.key"
    state: present

- name: Add InfluxData repository [Debian/Ubuntu]
  ansible.builtin.apt_repository:
    repo: deb {{ telegraf_repo_base_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ telegraf_install_version }}
    state: present

- name: Install Telegraf packages [Debian/Ubuntu]
  ansible.builtin.apt:
    name: telegraf
    state: latest
    update_cache: yes
