---
- name: Install any necessary dependencies [Debian/Ubuntu]
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Ensure apt key dir exists
  ansible.builtin.file:
    path: "{{ telegraf_repo_apt_key_dest | dirname }}"
    state: directory

- name: Install Telegraf apt key [Debian/Ubuntu]
  ansible.builtin.get_url:
    url: "{{ telegraf_repo_base_url }}/{{ telegraf_repo_apt_key_name }}"
    dest: "{{ telegraf_repo_apt_tmp_key_dest }}"

- name: Convert and copy apt repo key into apt format and dir (gpg)
  ansible.builtin.shell:
    cmd: "cat {{ telegraf_repo_apt_tmp_key_dest }} | gpg --dearmor | sudo tee {{ telegraf_repo_apt_key_dest }}"
  environment:
    MODULE_STRICT_UTF8_RESPONSE: "False"

- name: Add InfluxData repository [Debian/Ubuntu]
  ansible.builtin.apt_repository:
    repo: deb [signed-by={{ telegraf_repo_apt_key_dest }}] {{ telegraf_repo_base_url }}/{{ ansible_distribution | lower }} stable main
    state: present

- name: Install Telegraf packages [Debian/Ubuntu]
  ansible.builtin.apt:
    name: telegraf
    state: latest
    update_cache: yes
