---
# mediafellows.telegraf handlers

- name: restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted

- name: wait for startup
  listen: restart telegraf
  ansible.builtin.pause:
    seconds: 3
